### ISSUE TITLE
支持通过url上传文件到UPYUN

### ISSUE THREAD

**Issue by Wine93** [upyun/go-sdk#1]
通过url直接上传文件到UPYUN, 无需下载到本地再通过文件上传!
比如我在浏览网页时发现喜爱的图片, 想存储在UPYUN空间, 亦或者我在网页上需要下载一个大文件, 又想将这个文件存储在又拍云! 提供这个接口可以略去将资源下载到本地的步骤,  直接将资源存储到UPYUN
可复用接口`func (u *UpYun) Get(key string, value *os.File) error`, 使 value即可以接收`os.File`, 又可以接收`url`(interface{}可实现)! 
![http://img.baidu.com/orange.jpg](http://preview.quanjing.com/amana_rf005/10540000332.jpg)

**Comment by grinningorange** [comment]
@Wine93  确实可以这么做，但是官方的 SDK 应该提供的是最简单，最基本的功能。
类似支持通过 url 上传的功能，用户可以在代码里封装一层来实现。
不过，还是感谢提供第一个 issue。
