### ISSUE TITLE
Adding the purge API?

### ISSUE THREAD

**Issue by luanzhu** [upyun/go-sdk#4]
Hi, thanks for the excellent library!  I am wondering whether you are interested in adding the purge component to the library?  I wrote a simple one a couple of days ago based on your code.  Could you please take a look at the code?

https://github.com/upyun/go-sdk/compare/master...luanzhu:for-upyunpurge-pull-request

I will be more than happy to create a pull request if you like to include the purge component?  

Thanks a lot!

**Comment by grinningorange** [comment]
Before i do that, i think i'd do some optimizations and write a better readme.
But, pls, create a pull request, gonna catch up with that sometime(maybe in couple of weeks).
As i said before, thanks so much for doing all this!

**Comment by luanzhu** [comment]
Sounds like a good plan to me.  Just created the pull request.  Thank you!

**Comment by xxhhcc** [comment]
added
