### ISSUE TITLE
下载新版本 v3 报错

### ISSUE THREAD

**Issue by azhai** [upyun/go-sdk#52]
go: downloading github.com/upyun/go-sdk/v3 v3.0.0
go get: github.com/upyun/go-sdk/v3@v3.0.0: verifying module: checksum mismatch
	downloaded: h1:Qx/6C961SOicM/+a7PJW8K+e/0WLnwTZ9qfKFD/RnGQ=
	sum.golang.org: h1:AXmeuTWJp3oZUjXX/45RssJTndcxAbvGZqtsgKxuMIM=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by azhai** [comment]
解决方法
```bash
GOSUMDB=off go get -u github.com/upyun/go-sdk/v3
```

**Comment by huangnauh** [comment]
你的 go 版本多少，11.4 之前的版本有这个问题 https://github.com/golang/go/issues/29278

**Comment by huangnauh** [comment]
是代理没有更新 sum， 如果你在用 https://goproxy.io， 可以换一个， 比如 https://goproxy.cn
