### ISSUE TITLE
使用go get下载该包失败

### ISSUE THREAD

**Issue by NotZh** [upyun/go-sdk#54]
go: downloading github.com/upyun/go-sdk/v3 v3.0.0
go get github.com/upyun/go-sdk/v3/upyun: github.com/upyun/go-sdk/v3@v3.0.0: verifying module: checksum mismatch
	downloaded: h1:Qx/6C961SOicM/+a7PJW8K+e/0WLnwTZ9qfKFD/RnGQ=
	sum.golang.org: h1:AXmeuTWJp3oZUjXX/45RssJTndcxAbvGZqtsgKxuMIM=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by huangnauh** [comment]
You can upgrade to the latest version of go-sdk using:  go get -u github.com/upyun/go-sdk/v3
